name = "testLCS"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TestLCS", "generate-blog"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc4"

[[lean_lib]]
name = "TestLCS"


[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.29.0-rc4"

[[lean_exe]]
name = "generate-blog"
root = "TestLCS"
