import VersoManual
import DocsLCS.Section1

-- This gets access to most of the manual genre
open Verso.Genre Manual

-- This gets access to Lean code that's in code blocks, elaborated in the same process and
-- environment as Verso. Here, they're used to have the text refer to Verso code used in the text's
-- own source.
open Verso.Genre.Manual.InlineLean

-- This gets access to tools for showing Lean code that's loaded from external modules. need new
open Verso.Code.External


set_option pp.rawOnError true

set_option verso.exampleProject "../LCS"
set_option verso.exampleModule "LCS"


set_option verso.exampleModule "LCS.Basic"
#doc (Manual) "Formalisation of Linear Constraints Systems games in Lean4" =>
%%%
authors := ["Sean Perazzolo, Spring 2026"]
shortTitle := "LCS in Lean4"
%%%


{include 1 DocsLCS.Section1}


# Introduction to Linear Constraint System Games
_Placedholder text generated by LLM, to be replaced with original meaningfull content._

A Linear Constraint System (LCS) game is a type of nonlocal game that can be used to demonstrate quantum advantage. In an LCS game, two players, Alice and Bob, are given inputs and must produce outputs that satisfy certain linear constraints. The players are not allowed to communicate with each other during the game, but they can share entangled quantum states beforehand.

Alice generally receives an input that corresponds to a linear constraint, and she must produce an output that satisfies that constraint. Bob receives an input that corresponds to a variable in the constraints, and he must produce an output that is consistent with the constraints given Alice's outpt.


## Mermin Peres Magic Square Game
_Placedholder text generated by LLM, to be replaced with original meaningfull content._

The most famous example of an LCS game is the Mermin Peres Magic Square game. In this game, Alice and Bob are given a 3x3 grid of variables, and they must fill in the grid with 0s and 1s such that each row and column sums to an even number. Classically, it is impossible for Alice and Bob to win this game with probability 1, but if they share a specific entangled quantum state, they can win with probability 1.

# Formalising Linear Constraint System Games
_To even start proving anything about LCS games, we first need to formalise what an LCS game is and what is a valid strategy for a game. This involves defining the geometry of the game, the requirements for a strategy to be valid, and the specific values of the constraints that define the game._

All of the content below is defined in the module [LCS.Basic](./). 



## Defining the Layout of an LCS Game 
A LCS Game is defined by his sets of variables and constraints.

We choose to represent the geometry of the game using a structure called LCSLayout, which contains the following data:
- $`r` : the number of constraints (or questions for Alice)
- $`s` : the number of variables (or questions for Bob)
- $`V` : a function that takes an index i and returns the set of variables that are involved in the i-th constraint.


```anchor LCSLayout
structure LCSLayout where
  r : ℕ
  s : ℕ
  V : Fin r → Finset (Fin s)
```

Note that this layout does not contain any information about the specific values of the constraints, it only captures the geometry of the game, i.e. which variables are involved in which constraints. The specific values of the constraints will be captured in the definition of the LCS Game itself. This follows from the fact that a strategy for the game does not depend on the specific values of theconstraints, but only on the geometry of the game.


## Assignments

Assignemnt is an abreviation/aliases for the type, (function type)  that represents all possible assignments of values to the variables in V i. 

An assignement is defined for a specific LCS layout and a specific constraint i.
The assignment of the variable to the constraint i is represented as a function that takes a variable from $`V_i` and returns a value in $`Fin 2` (i.e. 0 or 1). This captures the idea that Alice must assign a value of 0 or 1 to each variable used in the i-th constraint.

Leans know that this is a function type that has a finite domain which will allow us for example to sum over all possible assignments in a finite way, which is important for the rest of the formalisation.


```anchor Assignment
abbrev Assignment (G : LCSLayout) (i : Fin G.r) : Type :=
  (G.V i) → Fin 2
```
## A LCS Game
So far we have defined the geometry of the game, and the requirement for a strategy to be valid without ever specifying the specific values of the constraints. However as we will need to talk about winning assignements or winning strategies, we need to define
the values of the contraints.

A LCS game is defined for a layout G. It is represent as a function that takes an index i to a value in $`ZMod 2` (i.e. 0 or 1). This captures the idea that the i-th constraint requires that the sum of the variables involved in that constraint must be equal to 0 or 1

```anchor LCSGame
structure LCSGame (G : LCSLayout) where
  b : Fin G.r → ZMod 2
```


## A Valid Strategy for an LCS Game
A strategy for an LCS game is modeled by a family of projectors for Alice and a family of projectors for Bob, that satisfy certain conditions. Specifically, the projectors for Alice must form a measurement system for each constraint, and the projectors for Bob must be consistent with the projectors for Alice in a certain way. This is captured by the definition of a valid strategy for an LCS game.

```anchor LCSStrategy
structure LCSStrategy
  (R : Type*) [Ring R] [StarRing R] [Algebra ℂ R]
  (G : LCSLayout) where
  E : ∀ i, (Assignment G i → R)
  F : Fin G.s → (Fin 2 → R)
  alice_ms : ∀ i, IsMeasurementSystem (E i)
  bob_ms   : ∀ j, IsMeasurementSystem (F j)
  commute  : ∀ i j α β, E i α * F j β = F j β * E i α
```

### Measurement Systems
The mathematical structure that captures the idea of a quantum measurement in the context of our LCS game.

```anchor IsMeasurementSystem (module := LCS.Basic) 
structure IsMeasurementSystem
  {I : Type*} [Fintype I]
  (f : I → R) : Prop where
  sum_one      : ∑ x, f x = 1
  idempotent   : ∀ x, f x * f x = f x
  orthogonal   : ∀ x y, x ≠ y → f x * f y = 0
  self_adjoint : ∀ x, star (f x) = f x
```


## Alice and Bob's Observables

Given a strategy for an LCS game, we can define the observables for Alice and Bob.
The observable for Alice corresponding to the variable j in the constraint i is defined as the difference between the sum of the projectors corresponding to the assignments that assign 0 to j and the sum of the projectors corresponding to the assignments that assign 1 to j.

For Bob, the observable corresponding to the variable j is defined as the difference between the projectors corresponding to the assignment that assigns 0 to j and the projectors corresponding to the assignment that assigns 1 to j. 

Alice and Bob's observables are completly defined by the LCSstrategy object, which contains the projectors for Alice and Bob. 

### Alice's observable

```anchor Alice_A
noncomputable def Alice_A
  {G : LCSLayout}
  {R : Type*} [Ring R] [StarRing R] [Algebra ℂ R]
  (strat : LCSStrategy R G) (i : Fin G.r) (j : G.V i) : R :=
  (∑ x ∈ Finset.univ.filter (fun (x : Assignment G i) => x j = 0), strat.E i x) -
  (∑ x ∈ Finset.univ.filter (fun (x : Assignment G i) => x j = 1), strat.E i x)
```
### Bob's observable

```anchor Bob_B
def Bob_B
  {R : Type*} [Ring R] [StarRing R] [Algebra ℂ R]
  {G : LCSLayout}
  (strat : LCSStrategy R G) (j : Fin G.s) : R :=
  strat.F j 0 - strat.F j 1
```
